---
title: "07.correlations"
author: "Aurora"
date: "7/2/2021"
output: html_document
---


```{r}
library("corrplot")
library(RColorBrewer)


df = read.table("data/all_input_data.csv", sep=",", head=T)
df = df[c(1,4,2,3,5:ncol(df))]
names(df)[c(3,4)] = c("flow1", "flow2")
```


```{r}
M<-cor(df[-1])
```

```{r}
pdf("figs/corplot.pdf")
corrplot(M, type="upper", tl.col="black", tl.srt=45,  col=brewer.pal(n=8, name="RdYlBu"))
dev.off()
```

```{r}
p.mat <- cor.mtest(df[-1])
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
pdf("figs/corplot2.pdf")
corrplot(M, method="color",col = brewer.pal(n=8, name="RdYlBu"),# col=col(200),  
         type="upper",# order="hclust", 
         addCoef.col = "black", # Add coefficient of correlation
         number.cex= 12/ncol(M),
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         p.mat = p.mat$p, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
         )
dev.off()
```

